const {
  REACT_APP_LOCAL_API_SERVER,
  REACT_APP_PROD_API_SERVER,
  REACT_APP_LOCAL_CLIENT,
  REACT_APP_PROD_CLIENT,
  REACT_APP_MODE,
} = process.env;

const isProd = REACT_APP_MODE === 'prod';
const REACT_APP_API_SERVER = isProd
  ? REACT_APP_PROD_API_SERVER
  : REACT_APP_LOCAL_API_SERVER;
const REACT_APP_CLIENT = isProd
  ? REACT_APP_PROD_CLIENT
  : REACT_APP_LOCAL_CLIENT;

export { REACT_APP_API_SERVER, REACT_APP_CLIENT };
